name: cargic_ninja
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_svg: ^0.19.1
  date_picker_timeline: ^1.2.1
  timeline_tile: ^1.0.0
# packages //back end
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  google_sign_in: "^4.5.1"
  firebase_database: ^4.1.1
  google_maps_flutter: ^1.0.3
  flutter_polyline_points: ^0.2.4
  geolocator: ^5.3.1
  http: ^0.12.2


  # packages // helpers
  provider: ^4.3.2+2
  connectivity: ^2.0.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.24
  # ext_storage: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  # Image assets
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  
  #  font assets
  fonts:
    - family: Niramit
      fonts:
        - asset: fonts/Niramit-Regular.ttf
        - asset: fonts/Niramit-Italic.ttf
        - asset: fonts/Niramit-Bold.ttf
  #         style: italic
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Italic.ttf
        - asset: fonts/Nunito-Bold.ttf

  #         weight: 700
    - family:  CargicIcons
      fonts:
       - asset: fonts/CargicIcons.ttf
    - family:  CargicSecondaryIcons
      fonts:
       - asset: fonts/CargicSecondaryIcons.ttf

 
        
